### ISSUE TITLE
incorrect message sending

### ISSUE THREAD

**Issue by Sorunome** [vranki/malobot#1]
just took a quick peek at the code.....your `send_html` method is confusing https://github.com/vranki/malobot/blob/master/bot.py#L10

It doesn't send a `formatted_body` but it does specify a `format`, that is invalid! If you want to send a plain text message, don't specify a `format` and if you want to send an HTML message you also need to specify a `formatted_body`

**Comment by vranki** [comment]
Thanks for reporting, fixed now.
