### ISSUE TITLE
Bot should auto-join a room on invite

### ISSUE THREAD

**Issue by anoadragon453** [vranki/malobot#2]
Ideally the bot would join a room when you invite it to it, otherwise you have to manually join new rooms through the bot's account.

The code I use for doing this in nio-template is https://github.com/anoadragon453/nio-template/blob/70d53a5abe13f85779201742cca50bc5b53ba338/main.py#L47 and https://github.com/anoadragon453/nio-template/blob/70d53a5abe13f85779201742cca50bc5b53ba338/callbacks.py#L68-L82

**Comment by vranki** [comment]
Added option to autojoin rooms. Check readme.
